chore: upgrading remix
gdg-uberlandia/pokedex pull request #19
Opened 2024-10-01 10:23 UTC by Luisgustavom1

2024-10-18 00:29 UTC, vilaboim requested changes

2024-10-18 00:29 UTC, vilaboim commented on app/components/Card/Card.tsx
> +export function Card({ children, title, className = "", articleProps }: Props) {
Pelo que percebi o `articleProps` está sendo usado para passar `className` para o componente, a prop `className` já resolveria (sendo usada em conjunto com a lib clsx que você instalou)?

2024-10-18 00:29 UTC, vilaboim commented on app/components/List/list.tsx
> +  return <main className="grid">{children}</main>;
Um `ul` não seria um melhor elemento para uma lista? E no `ListItem` talvez um `li` em vez do `section`?

2024-10-18 00:29 UTC, vilaboim commented on app/routes/profile.tsx
> +              Ver missoes
```suggestion
              Ver missões
```

2024-10-19 14:21 UTC, taciomedeiros approved these changes
Aprovado!

2024-10-19 14:22 UTC, merged